version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.1-apache  
    container_name: php_apache_server
    ports:
      - "8080:80"
    volumes:
      - ./frameworks:/var/www/html/UTU-project/frameworks
      - ./interfaz:/var/www/html/UTU-project/interfaz
      - ./logica:/var/www/html/UTU-project/logica
      - ./persistencia:/var/www/html/UTU-project/persistencia
    depends_on:
      - db
    
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root  # Password for the root user
      MYSQL_DATABASE: sigto       # Database to create
    ports:
      - "33060:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./others/sigto.sql:/docker-entrypoint-initdb.d/sigto.sql

volumes:
  db_data:
