version: "0.1"
networks:
  web_network:
    driver: bridge
    internal: true
  connection_network:
    driver: bridge

services:
  web-app-interface:
    image: httpd:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
      - web-app-logic
    networks:
      - web_network

  web-app-logic:
    image: php:latest
    volumes:
      -./persistencia/mysql:/usr/local/httpd/www/codesailing
    ports:
      -"8080:80"
    depends_on:
      - db
    networks:
      - web_network
      - connection_network

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "clap"
      MYSQL_USER: "juan"
      MYSQL_PASSWORD: "12345"
    restart: always
    volumes:
    - ./persistencia/mysql/:/var/lib/mysql
    ports:
      -"3306:3306"
    networks:
      - web_network
      - connection_network
