version: "3.0"
networks:
services:
  web-app-interface:
    image: http:latest
    ports:
      - "8080:8080"
    depends_on:
      - db
      - web-app-logic
    networks:
      - web_network

  web-app-logic:
    image: php:latest
    volumes:
      -./persistencia/mysql:/usr/local/httpd/www/codesailing
    ports:
      -"8080:80"
    depends_on:
      - db
    networks:
      - web_network
      - connection_network

  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: "sigto"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: ""
    volumes:
    - ./persistencia/mysql/:/var/lib/mysql
    ports:
      -"3306:3306"
    networks:
      - web_network
      - connection_network